config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :projects do
    resources :comments
  end
  resources :articles do
    resources :comments # /articles/id/comments/
  end

  get 'author_page' => 'articles#author_page'

  # Priority is based upon order of creation: first created -> highest priority
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically
  # ):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/article.rb
# Article data
class Article < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  # has_many :comments, dependent: :destroy
  has_many :comments, as: :commentable
end

app/controllers/articles_controller.rb
# Controls the data flow between the articles view and the article.rb model
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /articles
  # GET /articles.json
  def index
    @articles = policy_scope(Article)
  end

  def author_page
    @articles = policy_scope(Article)
    authorize @articles

    @article = Article
    @comments = policy_scope(Comment)
    @projects = policy_scope(Project)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    authorize @article unless @article.published
    @commentable = @article
    @comment = @commentable.comments.build # builds a comment w/ article_id
    @comments = policy_scope(@article.comments)
  end

  # GET /articles/new
  def new
    @article = Article.new
    @remote_value = true
  end

  # GET /articles/1/edit
  def edit
    authorize @article
    @remote_value = false
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    authorize @article

    save @article
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    authorize @article
    if @article.update(article_params)
      message = 'Article was successfully updated.'
      respond_to do |format|
        format.html { redirect_to @article, notice: message }
        format.js
      end
    else
      render :edit
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    authorize @article
    @article.destroy
    message = 'Article was successfully destroyed.'

    respond_to do |format|
      format.html { redirect_to articles_path, notice: message }
      format.js
    end
  end

  private

  def save(article)
    if article.save
      message = 'Article was successfully created.'
      current_user.articles << article
      respond_to do |format|
        format.html { redirect_to article, notice: message }
        format.js
      end
    else
      render :new
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def article_params
    params.require(:article).permit(
      *policy(@article || Article).permitted_attributes)
  end
end

app/helpers/articles_helper.rb
# Helpers for articles views
module ArticlesHelper
end

app/views/articles/_article.html.erb
<article class="large-12 columns" id=<%= "article-#{article.id}" %>>
  <h3><%= article.title %></h3>
  <p><%= article.body %></p>

  <%= link_to 'Show', article %>

  <% if policy(article).update? %>
    <%= link_to 'Edit', edit_article_path(article), id: 'edit_link_' + article.id.to_s %>
  <% end %>

  <% if policy(article).destroy? %>
    <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %>
  <% end %>
</article>

app/views/articles/_form.html.erb
<%= form_for(@article, remote: @remote_value) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %>
        prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <% if policy(@article).publish? %>
    <div class="field">
      <%= f.label(
        :published,
        title: "Is this article published?",
        data: { tooltip: true }) %><br>
      <%= f.check_box :published %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_form_comment.html.erb
<%= form_for([@article, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %>
        prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author, 'Name:' %><br>
    <%= f.text_area :author %>
  </div>

  <div class="field">
    <%= f.label :author_email, 'Email:' %><br>
    <%= f.text_area :author_email %>
  </div>

  <div class="field">
    <%= f.label :author_url, 'URL:' %><br>
    <%= f.text_area :author_url %>
  </div>

  <div class="field">
    <%= f.label :content, 'Comments:' %><br>
    <%= f.text_area :content %>
  </div>

<%
=begin %>
  <%= f.hidden_field :article_id, value: @article.id %>
<%
=end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/author_page.html.erb
<section class="row">
  <div class="large-offset-5 large-2 columns">
    <h1>Blog</h1>
    <% if @articles.count == 0 %>
      <p>Sorry, no articles as of yet. Come back soon!</p>
    <% end %>
  </div>

  <% if policy(@articles).create? %>
    <div class="large-12 columns">
      <%= link_to 'New Article', new_article_path %>
    </div>
  <% end %>
  <div class="large-12 columns">
    <%= link_to 'All Articles', articles_path %>
  </div>

  <section class="small-6 columns">
    <% @articles.each do |article| %>
      <article>
        <h3><%= article.title %></h3>
        <p><%= article.body %></p>

        <%= link_to 'Show', article %>

        <% if policy(article).update? %>
          <%= link_to 'Edit', edit_article_path(article) %>
        <% end %>

        <% if policy(article).destroy? %>
          <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </article>
    <% end %>
  </section>

<!-- FIXME: Querying DB directly from HTML. NO GOOD -->
  <section class="small-6 columns">
    <h3>Project comments waiting for Approval</h3>
    <% @projects.each do |project| %>
      <% project.comments.where(approved: false).each do |comment| %>
        <hr>
        <article>
          <h4><%= comment.commentable.name %> </h4>
          <h4><%= comment.author %></h4>
          <h4><%= comment.author_email %></h4>
          <h4><%= comment.author_url %></h4>

          <p><%= comment.content %></p>

          <%= form_for([comment.commentable, comment]) do |f| %>

            <div class="field">
              <%= f.label :approved %><br>
              <%= f.check_box :approved %>
            </div>

            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>
        </article>
      <% end %>
    <% end %>

    <h3>Article comments waiting for Approval</h3>
    <% @articles.each do |article| %>
      <% article.comments.where(approved: false).each do |comment| %>
        <hr>
        <article>
          <h4><%= comment.commentable.title %></h4>
          <h4><%= comment.author %></h4>
          <h4><%= comment.author_email %></h4>
          <h4><%= comment.author_url %></h4>

          <p><%= comment.content %></p>

          <%= form_for([comment.commentable, comment]) do |f| %>

            <div class="field">
              <%= f.label :approved %><br>
              <%= f.check_box :approved %>
            </div>

            <div class="actions">
              <%= f.submit %>
            </div>
          <% end %>

        </article>
      <% end %>
    <% end %>
  </section>
</section>

app/views/articles/create.js.erb
var ready = function () {
  $('#new_article').remove();
  $('#new-link').show();
  $('#articles-section').append('<%= j render(@article) %>');
};

$(document).ready(ready);
$(document).on('page:load', ready);

app/views/articles/destroy.js.erb
var ready = function () {
  $('#article-<%= @article.id %>').remove();
};

$(document).ready(ready());
$(document).on('page:load', ready());

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<section class="row" id="articles-section">
  <div class="large-offset-5 large-2 columns">
    <h1>Blog</h1>
    <% if @articles.count == 0 %>
      <p>Sorry, no articles as of yet. Come back soon!</p>
    <% end %>
  </div>

  <% if policy(@articles).create? %>
    <div class="large-12 columns">
      <%= link_to 'New Article', new_article_path, id: 'new-link', remote: true %>
    </div>
  <% end %>
  <% if policy(@articles).create? %>
    <div class="large-12 columns">
      <%= link_to 'My Articles', author_page_path %>
    </div>
  <% end %>

  <%= render @articles %>
</section>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/new.js.erb
var ready = function () {
  $('#new-link').hide().after('<%= j render("form") %>');
};

$(document).ready(ready);
$(document).on('page:load', ready);

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status:</b>
  <%= @article.published? ? "Published" : "Unpublished" %>
</p>

<p id="status">
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p id="author">
  <b>By: <%= @article.author.email %></b>
</p>

<p>
  <strong>Body:</strong>
  <%= @article.body %>
</p>

<% if policy(@article).destroy? %>
  <%= link_to 'Destroy', article_path(@article), method: :delete %> |
<% end %>
<% if policy(@article).update? %>
  <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>

<% @comments.each do |comment| %>
  <p><%= comment.author %></p>
  <p><%= comment.content %></p>
<% end %>

<% if policy(@comment).create? %>
  <%= render 'comment_partials/form_comment' %>
<% else %>
  <p>You must log in to comment</p>
<% end %>