config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :projects do
    resources :comments
  end
  resources :articles do
    resources :comments # /articles/id/comments/
  end

  get 'author_page' => 'articles#author_page'

  # Priority is based upon order of creation: first created -> highest priority
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically
  # ):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
# Project data
class Project < ActiveRecord::Base
  validates :technologies_used, presence: true
  validates :name, length: { in: 4..255 }

  belongs_to :author, class_name: 'User'
  has_many :comments,  as: :commentable
end

app/controllers/projects_controller.rb
# Controls the flow of data between the views/projects and project.rb model
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all
  end

  def show
    @commentable = @project
    @comment = @commentable.comments.build
    @comments = policy_scope(@project.comments)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      current_user.projects << @project
      flash[:notice] = 'Project was successfully created.'
      redirect_to @project
    else
      flash.now[:error] = 'Project could not be saved.'
      render :new
    end
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  private

  def project_params
    params.require(:project).permit(:name, :technologies_used, :image_url)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :technologies_used %><br />
    <%= f.text_area :technologies_used %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'projects/form' %>

<%= link_to "Cancel", :back %>

app/views/projects/new.html.erb
<h2>New project</h2>

<%= render 'projects/form' %>

<%= link_to "Back", projects_path %>

app/views/projects/show.html.erb
<% if @project.image_url %>
  <img src=<%= @project.image_url %>>
<% end %>
<h2><%= @project.name %></h2>
<p>Technologies used: <%= @project.technologies_used %></p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'Destroy', project_path(@project),
  method: :delete,
  data: { confirm: "Are you sure?" } %>

<% @comments.each do |comment| %>
  <p><%= comment.author %></p>
  <p><%= comment.content %></p>
<% end %>

<% if policy(@comment).create? %>
  <%= render 'comment_partials/form_comment' %>
<% end %>