config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }
  resources :projects do
    resources :comments
  end
  resources :articles do
    resources :comments # /articles/id/comments/
  end

  get 'author_page' => 'articles#author_page'

  # Priority is based upon order of creation: first created -> highest priority
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically
  # ):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Copyright 2014 by Philip Q Nguyen</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Blog", articles_path %></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="row">
  <div class="large-3 columns">
    <h1><img src="http://placehold.it/400x100&text=Logo"></h1>
  </div>
  <div class="large-9 columns">
    <ul class="button-group right">
      <li><%= link_to "Home", root_path, class: "button" %></li>
      <li><%= link_to "Blog", articles_path, class: "button" %></li>
      <li><%= link_to "Portfolio", projects_path, class: "button" %></li>

      <% if user_signed_in? %>
        <!-- FIXME: Code smell. Refactor to use Pundit -->
        <% if current_user.author? || current_user.editor? %>
          <li>
            <%= link_to "Author's Page", author_page_path, class: "button" %>
          </li>
        <% end %>
        <li>
          <%= link_to "Sign out", destroy_user_session_path, method: :delete,
          class: "button" %>
        </li>
      <% else %>
        <li>
          <%= link_to "Sign in", new_user_session_path, class: "button" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Phil's Portfolio</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
      <% flash.each do |key, value| %>
        <div class="alert-box round <%= flash_class(key) %>">
          <%= value %>
        </div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>